### ISSUE TITLE
Contact information unavailable on admin frontend

### ISSUE THREAD

**Issue by JMALindell** [fyysikkokilta/kulumasiina-v2#10]
Hyvää joulua ja niin eteenpäin. Rahis on töis

Kulumasiinasta ei löydy mistään (ainakaan helposti) formissa pyydettäviä yhteystietoja, joten nämä olisi kiva saada ainakin web-puolen fronttiin meikäläiselle näkyviin. Ei tarvitse pistää itse pdf-formeihin tuota kuitenkaan

**Comment by ApsiV11** [comment]
Hyvää joulua uudelta rahikselta. Mitä rahikset muuta tekis ku töitä :D

Tää näyttää unohtuneen lisätä tietokantaan kokonaan. Lisätty commitissa 576a9d252d0643dd3cd62a071ce8ed9364b6dd44.

Kun tää joskus viedään tuotantoon niin pitää ajella kantaan `ALTER TABLE entry ADD contact VARCHAR NOT NULL DEFAULT ''` tai vastaava komento.
