### ISSUE TITLE
Pilkkua tai pistettä ei voi kirjoittaa hintakenttään tietyillä puhelimilla

### ISSUE THREAD

**Issue by JMALindell** [fyysikkokilta/kulumasiina-v2#7]
Tietyillä käyttöliittymillä on mahdotonta kirjoittaa pelkällä puhelimen numerokentällä pilkkua/pistettä hintakenttään, jolloin desimaalisummien kirjoittaminen on myös mahdotonta.

![image](https://github.com/fyysikkokilta/kulumasiina-v2/assets/99137486/dd1effe0-72f9-4399-ba8b-e67ff4c10f41)

**Comment by Jaakkonen** [comment]
Should be fixed in latest commit

**Comment by ApsiV11** [comment]
Seems like this is still not fixed

**Comment by ApsiV11** [comment]
`The value decimal assures that along with digits from 0 to 9 the locale-specific decimal separator (“.” or “,”) must be displayed. ‘Minus’ key may or may not be displayed.`

https://www.geeksforgeeks.org/html-inputmode-attribute/

InputMode changed from `numeric `to `decimal`. Should be fixed now
